### ISSUE TITLE
Not working in RecyclerView

### ISSUE THREAD

**Issue by ilyassesalama** [eriffanani/TextViewReadMore#2]
The library seems excellent but it is just broken when used in RecyclerView as shown in the video. The list becomes very unstable and does not show the correct text and glitches around.

https://user-images.githubusercontent.com/46769766/181864997-5b36cf66-9496-4520-9185-348500c613e9.mp4

Moreover, the app crashes after scrolling up and down for a few seconds.
```
2022-07-30 02:20:19.547 19214-19214/com.application.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.application.app, PID: 19214
    java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(String.java:2064)
        at java.lang.String.subSequence(String.java:2107)
        at com.erif.readmoretextview.TextViewReadMore.onDraw(TextViewReadMore.java:135)
        at android.view.View.draw(View.java:22704)
        at android.view.View.updateDisplayListIfDirty(View.java:21579)
```

**Comment by eriffanani** [comment]
Hi, thanks for the feedback and helping me to test this library.  I will fix it as soon as possible.  Thanks again 🙏🙏

**Comment by eriffanani** [comment]
I am very happy with your feedback.

**Comment by ilyassesalama** [comment]
You're welcome. I forgot to mention that "Read more" text shows twice after clicking on it. You can see it in the video.

**Comment by eriffanani** [comment]
Hi [ilyassesalama](https://github.com/ilyassesalama), I've been updated my library, please check it and please give feedback again if you still have problems. Thank you

**Comment by ilyassesalama** [comment]
It seems like you used `setItemViewCacheSize` and that's definitely a bad idea for a list that is updated in realtime (chat app for instance). As well as it will affect the RecyclerView performance.

**Comment by eriffanani** [comment]
Hi [ilyassesalama](https://github.com/ilyassesalama), I've been updated my library, please check it and please give feedback again if you still have problems. Thank you

**Comment by ilyassesalama** [comment]
The app now only crashes, I can't test the library as before anymore.
```
java.lang.ArrayIndexOutOfBoundsException: length=15; index=20
        at android.text.StaticLayout.getEllipsisCount(StaticLayout.java:1341)
        at com.erif.readmoretextview.TextViewReadMore.isEllipsized(TextViewReadMore.java:194)
        at com.erif.readmoretextview.TextViewReadMore.buildSpan(TextViewReadMore.java:155)
        at com.erif.readmoretextview.TextViewReadMore.onMeasure(TextViewReadMore.java:149)
        at android.view.View.measure(View.java:25833)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25833)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6980)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25833)
```

Also, why the library's minSdk is 23 and not 21?

**Comment by eriffanani** [comment]
Hi [ilyassesalama](https://github.com/ilyassesalama), Can i see your xml code for showing this TextView ?

**Comment by eriffanani** [comment]
Hi [ilyassesalama](https://github.com/ilyassesalama), I've been updated my library, currently support for min sdk 21. Please check it and please give feedback again if you still have problems. Thank you.

**Comment by ilyassesalama** [comment]
It's nice that you're dedicated to working on this library. The latest update seems to be working well, but I noticed a few bugs as well as some suggestions.
- Sometimes the TextView shows 2 lines instead of 3 (maxLines) as it sometimes chops the custom `expandText` value.
- Read more/Close text doesn't have a space to separate itself from the original text.
- The animation is a bit unstable, I think you can't control that but it'd be great to add an attribute to disable the animation.
- You probably should remove ellipses (...) when `expandText` attribute is used to give the developer the option to use or not use them.

https://user-images.githubusercontent.com/46769766/183475014-4883d8dc-afb3-4972-89ae-390c07ca4c78.mp4

Also, what is `item.isCollapsed()` in the docs? I think it's to save the collapsed state, but how does it work exactly?

**Comment by eriffanani** [comment]
Hi [ilyassesalama](https://github.com/ilyassesalama), I've been fix my library
1. TextView shows unstable max lines (Fix)
2. Action button don't have a space (Fix)
3. The animation is a bit unstable (Fix)
4. Option to use or not (...) (Fix)
5. item.isCollapsed() is variable to storing state (collapse or expand) for RecyclerView Item

**Comment by ilyassesalama** [comment]
Excellent, everything seems very well so far. One last thing, I noticed some instability in the RecylcerView, but I think it's related to `item.isCollapsed()`. Can you update your sample project as well with this method (Java if possible) so I can give it a test to know where the issue is coming from?

**Comment by eriffanani** [comment]
what instability do you mean?  can you give me a more detailed sample video or picture?

**Comment by ilyassesalama** [comment]
The first one I noticed is the chopped "collapse" text. I tested here using Arabic characters by typing "إخفاء". The result:
![Screenshot_20220813-144926_مساري الدراسي](https://user-images.githubusercontent.com/46769766/184497154-b8966763-bde7-4045-8083-22adb692a666.png)

The second bug is that sometimes the TextView becomes like this:
![Screenshot_20220813-145016_مساري الدراسي](https://user-images.githubusercontent.com/46769766/184497179-0dd8f7bf-c507-4437-b916-7b260eb50c51.png)

**Comment by eriffanani** [comment]
Hi [ilyassesalama](https://github.com/ilyassesalama), I've been updated my library, please check it and please give feedback again if you still have problems. Thank you

**Comment by ilyassesalama** [comment]
It's been more than a year, crazy. Just saw your release in my profile. Anyway, I gave the library a test again. But it seems like it's completely broken inside of RecyclerView.

https://github.com/eriffanani/TextViewReadMore/assets/46769766/47bdcc21-cc28-4cc6-a814-6a4feccd503a

**Comment by eriffanani** [comment]
Hi, Ilyas. Thanks for reaching out to me about this bug. I have resolved this bug. You can see the video I have attached. Please stay up to date, I will update the library version as soon as possible. Thank You.

https://github.com/eriffanani/TextViewReadMore/assets/26743731/3a78a85e-db09-4e9a-b914-bd474fe8b376
